main: "net.defracted.witcherswords.Main"
version: "0.0.1"
name: "WitcherSwords"
author: "Defracted7"
api-version: "1.16"


commands:
  getaerondight:
    description: "Gives Aerondight"
    usage: "/getaerondight"
    permission: "witcher.get.aerondight"


permissions:
  witcher.*:
    default: false
    description: "Full access to Witcher Swords"
